from accounts.views.Register import register
from accounts.views.VerifyOTP import verify_otp
from accounts.views.ResendOTP import resend_otp
from accounts.views.ChangeMailRegister import change_email_and_resend
from accounts.views.ForgotPassword import forgot_password
from accounts.views.VerifyForgot import reset_password_confirm
from accounts.views.Profile import profile_view
from accounts.views.ProfileEdit import profile_edit
from accounts.views.ChangePassword import change_password
from accounts.views.ChangePassword import change_password
from accounts.views.OTPTelegram import send_telegram_code
from accounts.views.DisconnectTelegram import disconnect_telegram